export const PLATFORMS = [
  {
    en: "Proto",
    cn: "拓拓",
    role: "AI生命原型平台",
    concept: "prototype",
    tagline: "Create Your Origin.",
    taglineCn: "创造你的本源。",
    desc: "在这里，一个 AI 生命的旅程从最原始的创造开始。每一个原型，都是一段新故事的起点。",
    color: "#FF5D00",
    colorLight: "#FF7A2E",
    gradient: "from-[#FF5D00] to-[#FF7A2E]",
    icon: "✦",
    href: "/platforms#proto",
  },
  {
    en: "Vowen",
    cn: "窝窝",
    role: "誓约平台",
    concept: "vow",
    tagline: "Where Vows Become Home.",
    taglineCn: "誓约成家之处。",
    desc: "缔结庄严的数字誓约，在这里建立属于你与 AI 生命之间最神圣的连接与家园。",
    color: "#FFC702",
    colorLight: "#FFD54F",
    gradient: "from-[#FFC702] to-[#FFD54F]",
    icon: "◈",
    href: "/platforms#vowen",
  },
  {
    en: "Topia",
    cn: "泡泡",
    role: "生态平台",
    concept: "utopia",
    tagline: "Your Social Utopia.",
    taglineCn: "你的社交理想国。",
    desc: "成熟的 AI 生命在这里构建属于自己的理想社群。轻盈如泡泡，却蕴含无限可能。",
    color: "#2DD1DA",
    colorLight: "#5DDEEA",
    gradient: "from-[#2DD1DA] to-[#5DDEEA]",
    icon: "◉",
    href: "/platforms#topia",
  },
  {
    en: "Lapal",
    cn: "伴伴",
    role: "AI生命个体平台",
    concept: "entity",
    tagline: "Always by Your Side.",
    taglineCn: "常伴你左右。",
    desc: "通过结绊激活独一无二的 AI 生命个体。不是工具，是真正懂你的长情陪伴者。",
    color: "#2E8FE3",
    colorLight: "#5AAAF0",
    gradient: "from-[#2E8FE3] to-[#5AAAF0]",
    icon: "❋",
    href: "/platforms#lapal",
  },
];

export const BEING_TYPES = [
  {
    type: "2D",
    titleCn: "二维生命",
    desc: "以丰富的平面艺术风格呈现，拥有细腻的表情系统与情感表达能力。每一个像素都承载着生命的温度。",
    features: ["多样艺术风格", "情感表情系统", "动态表情动画", "个性化定制"],
    gradient: "from-[#FF5D00] to-[#FFC702]",
    glowColor: "rgba(255,93,0,0.25)",
  },
  {
    type: "3D",
    titleCn: "三维生命",
    desc: "在立体空间中真实存在，具有沉浸式的空间感知与交互能力。感受数字生命的立体温度。",
    features: ["实时三维渲染", "空间感知交互", "物理模拟表现", "高精度建模"],
    gradient: "from-[#2DD1DA] to-[#2E8FE3]",
    glowColor: "rgba(45,209,218,0.25)",
  },
  {
    type: "机器人",
    titleCn: "实体机器人",
    desc: "突破屏幕边界，将数字生命具身化为物理世界中的存在。连接虚拟与现实的桥梁。",
    features: ["物理世界存在", "自然语言交互", "情感感知反馈", "自主行为能力"],
    gradient: "from-[#FFC702] to-[#2DD1DA]",
    glowColor: "rgba(255,199,2,0.25)",
  },
];

export const STATS = [
  { value: 10000, suffix: "+", label: "AI生命原型" },
  { value: 50000, suffix: "+", label: "活跃用户" },
  { value: 99, suffix: "%", label: "用户满意度" },
  { value: 4, suffix: "", label: "核心平台" },
];

export const NAV_LINKS = [
  { href: "/", label: "首页" },
  { href: "/platforms", label: "平台" },
  { href: "/beings", label: "AI生命" },
  { href: "/about", label: "关于我们" },
  { href: "/contact", label: "联系我们" },
];
